#!/usr/bin/env bash

## correr directamente con la imagen de ultralytics: no es compatible con GPUs viejas

# Set image name as a variable
#t=ultralytics/ultralytics:latest
t=ultralytics/ultralytics:latest-jetson-jetpack6

# Pull the latest Ultralytics image from Docker Hub
sudo docker pull $t

# Run the container
xhost +local:docker && docker run -e DISPLAY=$DISPLAY \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v ~/.Xauthority:/root/.Xauthority \
  -v $(pwd)/weights:/app/weights \
  --device /dev/video0:/dev/video0 \
  -it --ipc=host --runtime=nvidia --gpus all $t \
  yolo predict model=/app/weights/merged/best.pt source=/dev/video0 show=True
